#cloud-config
users:
  - default
  - name: rocky
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID9V5yVND71p6KNr90wuHe54PUcBHgOZUxY8jFumC7ai

packages:
  - sudo

runcmd:
  - echo AuthenticationMethods publickey >> /etc/ssh/sshd_config
